apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: langchain-app
      tier: backend
  template:
    metadata:
      labels:
        app: langchain-app
    spec:
      containers:
      - name: langchain-container
        image: us-east1-docker.pkg.dev/linkedlens-452503/test-repo/langchain-app
        ports:
        - containerPort: 80
        env:
        - name: GOOGLE_API_KEY
          value: ${{secrets.GOOGLE_API_KEY}}