name: Setup, Build, Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-build-deploy-push:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'linkedlens-452503'
          workload_identity_provider: 'projects/57295351120/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc'
          service_account: ${{secrets.SERVICE_ACCOUNT}}
      
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'test-cluster'
          location: 'us-east1'
      
      - id: 'get-pods'
        run: 'kubectl get pods'

      - name: 'Setup Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud cli'
        run: 'gcloud info'
      
      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker us-east1-docker.pkg.dev
      
      - name: Build image
        run: docker build . --file . --tag us-east1-docker.pkg.dev/linkedlens-452503/test-repo
        working-directory: .
      
      - name: Docker push
        run: docker push us-east1-docker.pkg.dev/linkedlens-452503/test-repo